package com.eirs.pairs.alerts.constants;

public enum AlertIds {

    CONFIGURATION_VALUE_MISSING, CONFIGURATION_VALUE_WRONG, DATABASE_EXCEPTION, DATABASE_TABLE_EXCEPTION,NOTIFICATION_SEND_EXCEPTION,
    SMS_VALUE_MISSING, MODULE_EXECUTED_WITH_EXCEPTION;
}
